runtime: go113

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always

includes:
- env.yaml

automatic_scaling:
  max_idle_instances: 1
